spring:
  jpa:
    hibernate:
      ddl-auto: create  # 운영 환경에서는 "update" 또는 "validate" 권장
    show-sql: true      # SQL 쿼리 출력 활성화
    properties:
      hibernate:
        use_reflection_optimizer: false
        format_sql: true  # SQL 포맷팅
  messages:
    basename: message, errors
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cooking_recipe?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 0309
  thymeleaf:
    cache: false  # Thymeleaf 캐시 비활성화
  mvc:
    hiddenmethod:
      filter:
        enabled: true  # HiddenHttpMethodFilter 활성화
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  web:
    resources:
      static-locations: classpath:/static/, file:C:/Users/user/.gradle/cookingrecipe/uploaded-images/
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 2e7c317af863128ca7f60f4ff69217cf # REST API 키
            client-secret: ""              # 카카오는 secret 값이 필요하지 않음
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao" # 기본 Redirect URI - baseUrl 설정
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope: profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

file:
  upload-dir: C:/Users/user/.gradle/cookingrecipe/uploaded-images/ # 파일 업로드 경로

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG  # Spring Security 디버그 모드

redis:
  host: 127.0.0.1               # Redis 서버 호스트
  port: 6379                    # Redis 기본 포트
  password:                     # 필요 시 비밀번호 설정
  timeout: 5000                 # 연결 시간 초과 (ms)
  database: 0                   # 사용할 Redis 데이터베이스 (기본값: 0)
  lettuce:
    pool:
      max-active: 10            # 최대 활성 연결
      max-idle: 10              # 최대 유휴 연결
      min-idle: 1               # 최소 유휴 연결
